nome = "Luiza Cardoso"
idade = "33 anos"
telefone = 11978645277
endereço = "Rua Montenegro"
numerodacasa = 54
cidade = "Barueri"
cep = 06657410
cpf = 42317677823
rg = 486245184

console.log("O nome do contato é " + nome, ",ela tem " + idade); 
console.log("O numero de contato dela é " + telefone); 
console.log("Mora no endereço " + endereço, ",com o numero " + numerodacasa, "da residencia, na cidade de " + cidade, ",com o cep " + cep);
console.log("Numero de CPF " + cpf, "e RG" + rg);

